spring.application.name=TransferService

spring.jpa.defer-datasource-initialization=true

server.port=8081

account.service.url=${ACCOUNT_SERVICE_URL:http://localhost:8082}
fraud.service.url=${FRAUD_SERVICE_URL:http://localhost:8083}


spring.security.oauth2.client.registration.keycloak.client-id=transfer-service
spring.security.oauth2.client.registration.keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET}
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.keycloak.scope=openid

spring.security.oauth2.client.provider.keycloak.token-uri=${KEYCLOAK_TOKEN_URI:http://localhost:8080/realms/banking/protocol/openid-connect/token}


logging.level.org.springframework.security.oauth2=DEBUG
logging.level.org.springframework.security=DEBUG



spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/transfer_db}

spring.datasource.username= ${DB_USERNAME:postgres}
spring.datasource.password= ${DB_PASSWORD:postgres}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.sql.init.mode=always