spring.application.name=TransferService

spring.jpa.defer-datasource-initialization=true

server.port=8081

account.service.url=${ACCOUNT_SERVICE_URL:http://localhost:8082}
fraud.service.url=${FRAUD_SERVICE_URL:http://localhost:8083}